
#include "StandardKeyboardEvents.h"

#include "../Lua/LuaEnvironment.h"

namespace PE {
namespace Events {

	PE_IMPLEMENT_CLASS1(Event_KEY_A_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_S_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_D_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_W_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_PERIOD_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_COMMA_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_K_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_L_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_X_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_C_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_V_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_B_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_N_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_M_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_DOWN_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_UP_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_O_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_P_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_T_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_Y_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_J_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_H_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_Z_HELD, Event);

	PE_IMPLEMENT_CLASS1(Event_KEY_LEFT_BRACKET_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_RIGHT_BRACKET_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_ZERO_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_MINUS_HELD, Event);
	PE_IMPLEMENT_CLASS1(Event_KEY_EQUAL_HELD, Event);
};
};
